version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: sh -c "
      alembic upgrade head &&
      uvicorn main:app --host 0.0.0.0 --port 8080 --reload"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URI: ${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}


volumes:
  postgres_data: