version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: sh -c "
      alembic upgrade head &&
      pytest --cov=. --cov-report=term tests.py &&
      exit 0"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URI: ${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}